[project]
name = "shilp-setu-main"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi",
    "psycopg2-binary",
    "pwdlib[argon2] ",
    "pydantic-settings",
    "pyjwt",
    "python-dotenv",
    "sqlalchemy",
    "uvicorn",
    "aiosqlite",
    "fastapi-users[sqlalchemy]",
    "imagekitio",
    "python-multipart",
]

[project.scripts]
shilp-setu-main = "shilp_setu_main:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
